ego coordinate system
zbzhu99/NGSIM_Imitation pull request #2
Opened 2022-04-08 04:32 UTC by YuechengLiu

2022-04-08 12:47 UTC, zbzhu99 requested changes

2022-04-08 12:47 UTC, zbzhu99 commented on smarts-imitation/smarts_imitation/utils/adapter.py
> +        ego_dynamics=(1,),
If the ego position is not included in the current observation, the `DistanceTravelled` metric can not be computed in eval_util.py.

2022-04-08 12:47 UTC, zbzhu99 commented on smarts-imitation/smarts_imitation/envs/core.py
> +            shape=(12 * self.obs_stack_size,),
I suggest change the magic number here as an attribute from self.agent_spec.observation_adapter.

Now observation_adapter is a function, and we can change it as a class with `__call__` overrided with an additional attribute as obs_dim.

2022-04-08 12:47 UTC, zbzhu99 commented on smarts-imitation/smarts_imitation/utils/adapter.py
> +        )
I have to keep this kind of 4-dimensional ego observation here to make sure some of the previous experiment results can be reproduced.

2022-04-10 02:19 UTC, zbzhu99 commented
Also, plz format the code using `black` to make CI test pass :dizzy:, thanks~

(For more info about black, you can refer to https://black.readthedocs.io/en/stable/.)

2022-04-10 03:56 UTC, YuechengLiu commented
> Also, plz format the code using `black` to make CI test pass 💫, thanks~
> 
> (For more info about black, you can refer to https://black.readthedocs.io/en/stable/.)

2022-04-10 10:41 UTC, YuechengLiu reviewed
great

2022-04-10 13:09 UTC, zbzhu99 approved these changes

2022-04-10 13:09 UTC, zbzhu99 commented on ILSwiss/run_scripts/gen_smarts_demos.py
> +            "smarts_{}_stack-{}.pkl".format(
I do not quite understand how do we distinguish demonstration data with different feature_list?

2022-04-10 13:10 UTC, merged